# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sudoku_face.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Sudoku(object):
    def setupUi(self, Sudoku):
        Sudoku.setObjectName(_fromUtf8("Sudoku"))
        Sudoku.setWindowModality(QtCore.Qt.NonModal)
        Sudoku.resize(405, 487)
        self.centralwidget = QtGui.QWidget(Sudoku)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 180, 405, 3))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(0, 225, 405, 3))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_14 = QtGui.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(180, 0, 3, 405))
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.line_13 = QtGui.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(135, 0, 3, 405))
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.line_17 = QtGui.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(315, 0, 3, 405))
        self.line_17.setFrameShape(QtGui.QFrame.VLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.line_18 = QtGui.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(360, 0, 3, 405))
        self.line_18.setFrameShape(QtGui.QFrame.VLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 135, 405, 3))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_1 = QtGui.QFrame(self.centralwidget)
        self.line_1.setGeometry(QtCore.QRect(0, 45, 405, 3))
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName(_fromUtf8("line_1"))
        self.line_16 = QtGui.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(270, 0, 3, 405))
        self.line_16.setFrameShape(QtGui.QFrame.VLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 90, 405, 3))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(0, 270, 405, 3))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_12 = QtGui.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(90, 0, 3, 405))
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(0, 315, 405, 3))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(0, 360, 405, 3))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.line_15 = QtGui.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(225, 0, 3, 405))
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.line_11 = QtGui.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(45, 0, 3, 405))
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 410, 105, 25))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(325, 410, 80, 25))
        self.lineEdit.setMaxLength(5)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 410, 80, 25))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 405, 405, 3))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        Sudoku.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Sudoku)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 405, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuLEVEL = QtGui.QMenu(self.menubar)
        self.menuLEVEL.setObjectName(_fromUtf8("menuLEVEL"))
        self.menuHELP = QtGui.QMenu(self.menubar)
        self.menuHELP.setObjectName(_fromUtf8("menuHELP"))
        Sudoku.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Sudoku)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Sudoku.setStatusBar(self.statusbar)
        self.actionEasy = QtGui.QAction(Sudoku)
        self.actionEasy.setObjectName(_fromUtf8("actionEasy"))
        self.actionMiddle = QtGui.QAction(Sudoku)
        self.actionMiddle.setObjectName(_fromUtf8("actionMiddle"))
        self.actionHard = QtGui.QAction(Sudoku)
        self.actionHard.setObjectName(_fromUtf8("actionHard"))
        self.menuLEVEL.addAction(self.actionEasy)
        self.menuLEVEL.addAction(self.actionMiddle)
        self.menuLEVEL.addAction(self.actionHard)
        self.menubar.addAction(self.menuLEVEL.menuAction())
        self.menubar.addAction(self.menuHELP.menuAction())

        self.retranslateUi(Sudoku)
        QtCore.QMetaObject.connectSlotsByName(Sudoku)

    def retranslateUi(self, Sudoku):
        Sudoku.setWindowTitle(_translate("Sudoku", "MainWindow", None))
        self.pushButton.setText(_translate("Sudoku", "PushButton", None))
        self.menuLEVEL.setTitle(_translate("Sudoku", "LEVEL", None))
        self.menuHELP.setTitle(_translate("Sudoku", "HELP", None))
        self.actionEasy.setText(_translate("Sudoku", "Easy", None))
        self.actionMiddle.setText(_translate("Sudoku", "Middle", None))
        self.actionHard.setText(_translate("Sudoku", "Hard", None))

